version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_3026Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_git_3026.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:TestDB
  packages:
  - name: SIQA_GIT_3026Project
    version: "1.0"
- serviceName: project.siqa_git_3026.integrations:Test_AdapterScaffolding
  packages:
  - name: SIQA_GIT_3026Project
    version: "1.0"
